Metadata:
  License: Apache-2.0
AWSTemplateFormatVersion: '2010-09-09'
Description: Asociaciones
Parameters:
  InstanceType:
    Description: WebServer Ec2 instance
    Type: String
    Default: t2.micro
    AllowedValues: [t2.micro, t3.small]
    ConstraintDescription: validar EC2 instance type
  KeyName:
    Description: escoje K-ORE-GREEN
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: debe ser el nombre de una existente KeyPair
  SSHLocation:
    Description: IP range to SSH to EC2 instance
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: debe ser un IP CIDR valido
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      UserData: !Base64 
        Fn::Join:
        - ''
        - [IPAddress=, !Ref 'IPAddress']
      InstanceType: !Ref 'InstanceType'
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'LatestAmiId'
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref 'SSHLocation'
  IPAddress:
    Type: AWS::EC2::EIP
  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref 'EC2Instance'
      EIP: !Ref 'IPAddress'

Outputs:
  InstanceId:
    Description: instance id de la nueva instancia creada
    Value: !Ref 'EC2Instance'
  InstanceIPAddress:
    Description: IP address de la nueva instancia creada
    Value: !Ref 'IPAddress'
